### ISSUE TITLE
Error while running Capturer

### ISSUE THREAD

**Issue by SivaKesava1** [cyrus-and/chrome-har-capturer#38]
When I run
google-chrome --remote-debugging-port=9222  --enable-benchmarking  --enable-net-benchmarking
A new window opens but in the terminal I am seeing this

> [16210:16210:0315/175447.814565:ERROR:child_thread_impl.cc(762)] Request for unknown Channel-associated interface: ui::mojom::GpuMain

In another terminal when I run
chrome-har-capturer -o out.har  https://github.com
I am seeing this error

```
/usr/local/lib/node_modules/chrome-har-capturer/node_modules/chrome-remote-interface/node_modules/ws/lib/PerMessageDeflate.js:8
const TRAILER = Buffer.from([0x00, 0x00, 0xff, 0xff]);
                       ^

TypeError: this is not a typed array.
    at Function.from (native)
    at Object.<anonymous> (/usr/local/lib/node_modules/chrome-har-capturer/node_modules/chrome-remote-interface/node_modules/ws/lib/PerMessageDeflate.js:8:24)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/chrome-har-capturer/node_modules/chrome-remote-interface/node_modules/ws/lib/WebSocket.js:16:27)
    at Module._compile (module.js:410:26)
```

I have nodejs version v4.2.6
Chrome Version 57.0.2987.98 (64-bit)

Please help me in getting this project to be able to run on my system.

**Comment by cyrus-and** [comment]
That error happens in the [ws][1] library that I'm using. It [seems][2] that it requires Node.js version v4.5.0.

I don't know what your setup is, but it's fairly easy to download and use the [latest stable Node.js][3], if you don't have a privileged access on your test machine remember that you can just extract it in your home and run it from there:

```console
$ wget https://nodejs.org/dist/v6.10.0/node-v6.10.0-linux-x64.tar.xz
$ tar xf node-v6.10.0-linux-x64.tar.xz
$ node-v6.10.0-linux-x64/bin/node --version
v6.10.0
```

[1]: https://github.com/websockets/ws
[2]: https://nodejs.org/docs/v4.5.0/api/buffer.html#buffer_class_method_buffer_from_arraybuffer
[3]: https://nodejs.org/dist/v6.10.0/node-v6.10.0-linux-x64.tar.xz

**Comment by SivaKesava1** [comment]
Yes, the nodejs version was the problem. I installed version 6 and it was fine. Thanks for your quick replies.

**Comment by cyrus-and** [comment]
You're welcome!
